# Generated by Django 4.0.5 on 2022-06-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('parent_name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('number', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Joined_date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('F', 'Female')], max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department')),
            ],
        ),
    ]
