# Generated by Django 4.0.5 on 2022-06-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_students_admission_number_alter_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Joined_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
