# Generated by Django 4.0.5 on 2022-06-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_students_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Joined_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
