# Generated by Django 4.0.5 on 2022-06-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_students_gender_alter_students_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Hod',
        ),
    ]
